import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/ui/Navigation";
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Naess Shipping Philippines Incorporated",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <Navigation
          logoWhite="/images/naess-logo-white.png"
          logoBlack="/images/naess-logo-black.png"
        />
        {children}
        <Toaster 
          position="bottom-right" 
          toastOptions={{
            style: {
              fontSize: '18px',
              padding: '1rem',
            },
          }}
        />
      </body>
    </html>
  );
}
